# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: enja <enja@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/27 16:35:18 by enja              #+#    #+#              #
#    Updated: 2023/08/27 16:40:42 by enja             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Bureaucrat

SRC = main.cpp Bureaucrat.cpp

FLAGS = 

CC = c++

all : $(NAME)

$(NMAE) : $(SRC)

		$(CC) $(SRC) $(FLAGS) -o $(NAME)

fclean : 
		rm -rf $(NAME)

clean : clean

re : fclean all