# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ky05h1n <ky05h1n@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/27 16:35:18 by enja              #+#    #+#              #
#    Updated: 2023/08/29 22:46:47 by ky05h1n          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Bureaucrat

SRC = main.cpp Bureaucrat.cpp

FLAGS = -Wall -Wextra -Werror

CC = c++

all : $(NAME)

$(NMAE) : $(SRC)

		$(CC) $(SRC) $(FLAGS) -o $(NAME)

fclean : 
		rm -rf $(NAME)

clean : clean

re : fclean all